CREATE TABLE form (
    date_entered date,
    date_needed date,
    company character varying(50),
    jobnumber character varying(50),
    map_no character varying(10),
    contact character varying(50),
    phone character varying(50),
    notes character varying(500),
    certify_to character varying(50),
    lender character varying(50),
    gf_no character varying(50),
    address_street character varying(200),
    city character varying(50),
    state character varying(50),
    zipcode character varying(50),
    country character varying(50),
    survey_type character varying(10),
    county character varying(50),
    subdivision character varying(50),
    unit character varying(50),
    sub_block character varying(50),
    state character varying(50),
    lot character varying(50),
    survey character varying(50),
    rural_block character varying(50),
    rural_section character varying(50),
    meridian character varying(10),
    t_r character varying(10),
    plss_section character varying(50),
    folder_path character varying(300),
);